// client/src/components/Footer.tsx
export default function Footer() {
  return (
    <>
      <div className="bg-black p-4 text-white flex items-center">
        <div className="justify-self-start opacity-70 flex items-center gap-2 text-2xl">
          <span className="fa-brands fa-react"></span>
          <span className="fa-brands fa-node-js"></span>
        </div>
        <div className="text-center justify-self-center w-full">
          <span className="opacity-70">
            <a
              href="https://harelog3.github.io/bio-links/"
              className="hover:underline"
              target="_blank"
            >
              Harel Olguín
            </a>{" "}
            &copy; All rights reserved
          </span>
        </div>
        <div className=" justify-self-end">
          <a
            className="hover:opacity-100 opacity-70 transition-opacity"
            href="https://github.com/harelog3/judge-my-portfolio"
            target="_blank"
          >
            <i className="fa-brands fa-github text-3xl"></i>
          </a>
        </div>
      </div>
    </>
  );
}

// client/src/layouts/main/Footer.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts"></script>

<template>
  <div class="bg-black p-4 text-white flex items-center">
    <div class="justify-self-start opacity-70 flex items-center gap-2 text-2xl">
      <i class="fa-brands fa-vuejs"></i>
      <i class="fa-brands fa-node-js"></i>
    </div>
    <div class="text-center justify-self-center w-full">
      <span class="opacity-70"> Studium Team &copy; All rights reserved </span>
    </div>
    <div class="justify-self-end">
      <a
        class="hover:opacity-100 opacity-70 transition-opacity"
        href="https://github.com/harelog3/judge-my-portfolio"
        target="_blank"
      >
        <i class="fa-brands fa-github text-3xl"></i>
      </a>
    </div>
  </div>
</template>
